/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estante.janelas;

import estante.classes.Artigo;
import estante.classes.Autor;
import estante.classes.Editora;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Flavia
 */
public class JanelaCadastro extends javax.swing.JFrame {
    JanelaPrincipal janelaPrincipal;
    /**
     * Creates new form JanelaCadastro
     * @param janelaPrincipal
     */
    public JanelaCadastro(JanelaPrincipal janelaPrincipal) {
        initComponents();
        this.janelaPrincipal = janelaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeDaRevista = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMancheteDaRevista = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDiaDaPublicacao = new javax.swing.JTextField();
        jTextFieldMesDaPublicacao = new javax.swing.JTextField();
        jTextFieldAnoDaPublicacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNumeroDaEdicao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNomeDaEditora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldEditorial = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArtigosDaRevista = new javax.swing.JTable();
        jButtonCadastrarRevista = new javax.swing.JButton();
        jButtonLimparCamposDeCadastro = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonAdicionarArtigo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Dados da Revista");

        jLabel2.setText("Nome");

        jLabel3.setText("Manchete");

        jLabel4.setText("Data de Publicação");

        jTextFieldAnoDaPublicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnoDaPublicacaoActionPerformed(evt);
            }
        });

        jLabel5.setText("/");

        jLabel6.setText("/");

        jLabel7.setText("Nº Edição");

        jLabel8.setText("Editora");

        jLabel9.setText("Linha Editorial");

        jLabel10.setText("Artigos Favoritos");

        jTableArtigosDaRevista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título do artigo", "Autores", "Palavras-chave"
            }
        ));
        jScrollPane1.setViewportView(jTableArtigosDaRevista);

        jButtonCadastrarRevista.setText("Cadastrar");
        jButtonCadastrarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarRevistaActionPerformed(evt);
            }
        });

        jButtonLimparCamposDeCadastro.setText("Limpar");
        jButtonLimparCamposDeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparCamposDeCadastroActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonAdicionarArtigo.setText("Adicionar Artigo");
        jButtonAdicionarArtigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarArtigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomeDaRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMancheteDaRevista))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNomeDaEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDiaDaPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMesDaPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnoDaPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNumeroDaEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldEditorial)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLimparCamposDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastrarRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdicionarArtigo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeDaRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMancheteDaRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDiaDaPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnoDaPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldMesDaPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNumeroDaEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNomeDaEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButtonAdicionarArtigo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarRevista)
                    .addComponent(jButtonLimparCamposDeCadastro)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAnoDaPublicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnoDaPublicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnoDaPublicacaoActionPerformed

    private void jButtonCadastrarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarRevistaActionPerformed
        // TODO add your handling code here:
        //Capturando os dados da jTable que contém os artigos da revista
        if(this.jTextFieldNomeDaRevista.getText().isEmpty() 
                || this.jTextFieldMancheteDaRevista.getText().isEmpty()
                || this.jTextFieldNumeroDaEdicao.getText().isEmpty()
                || this.jTextFieldNomeDaEditora.getText().isEmpty()
                || this.jTextFieldEditorial.getText().isEmpty()
                || this.jTextFieldAnoDaPublicacao.getText().isEmpty()
                || this.jTextFieldMesDaPublicacao.getText().isEmpty()
                || this.jTextFieldDiaDaPublicacao.getText().isEmpty()){
            // show a joptionpane dialog using showMessageDialog
            JFrame frame = new JFrame("Cadastro");
            JOptionPane.showMessageDialog(frame,
                "Existem campos em branco na janela de cadastro",
                "Cadastro",
                JOptionPane.ERROR_MESSAGE);
            //this.setVisible(false);
        }else{
            List<Artigo> artigos = new ArrayList<>();
            Artigo artigo = new Artigo();
            for(int x = 0; x < this.jTableArtigosDaRevista.getRowCount(); x++){
                artigo.setTitulo(this.jTableArtigosDaRevista.getValueAt(x, 0).toString());

                String[] splitAutores = String.valueOf(this.jTableArtigosDaRevista.getValueAt(x, 1)).split(Pattern.quote(", "));
                for(String nome : splitAutores){
                    artigo.getAutores().add(new Autor(nome));
                }

                String[] splitPalavrasChave = String.valueOf(this.jTableArtigosDaRevista.getValueAt(x, 2)).split(Pattern.quote(", "));
                for(String palavra : splitPalavrasChave){
                    artigo.getPalavrasChave().add(palavra);
                }
                artigos.add(artigo);
            }
            //Chamada do método da estante que lança os dados da janela em uma instância de Revista
            this.janelaPrincipal.estante.adicionarRevistaAEstante(this.jTextFieldNomeDaRevista.getText(),
                    this.jTextFieldMancheteDaRevista.getText(),
                    Integer.parseInt(this.jTextFieldNumeroDaEdicao.getText()),
                    new Editora(this.jTextFieldNomeDaEditora.getText()),
                    this.jTextFieldEditorial.getText(),
                    LocalDate.of(Integer.parseInt(this.jTextFieldAnoDaPublicacao.getText()),
                        Integer.parseInt(this.jTextFieldMesDaPublicacao.getText()),
                        Integer.parseInt(this.jTextFieldDiaDaPublicacao.getText())),
                    artigos);
            // show a joptionpane dialog using showMessageDialog
            JFrame frame = new JFrame("Cadastro");
            JOptionPane.showMessageDialog(frame,
                "Nova revista adicionada com sucesso!",
                "Cadastro",
                JOptionPane.INFORMATION_MESSAGE);
            //Fechamento da janela
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonCadastrarRevistaActionPerformed

    private void jButtonAdicionarArtigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarArtigoActionPerformed
        // TODO add your handling code here:
        //System.out.println("Linhas existentes: " + this.jTableArtigosDaRevista.getRowCount());
        DefaultTableModel modeloDaLinha = (DefaultTableModel) this.jTableArtigosDaRevista.getModel();
        modeloDaLinha.addRow(new Object[]{null, null, null});

    }//GEN-LAST:event_jButtonAdicionarArtigoActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Fechamento da janela
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonLimparCamposDeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCamposDeCadastroActionPerformed
        // TODO add your handling code here:
        this.jTextFieldNomeDaRevista.setText("");
        this.jTextFieldMancheteDaRevista.setText("");
        this.jTextFieldNumeroDaEdicao.setText("");
        this.jTextFieldNomeDaEditora.setText("");
        this.jTextFieldEditorial.setText("");
        this.jTextFieldAnoDaPublicacao.setText("");
        this.jTextFieldMesDaPublicacao.setText("");
        this.jTextFieldDiaDaPublicacao.setText("");
        DefaultTableModel modelo = (DefaultTableModel) this.jTableArtigosDaRevista.getModel();
        while (this.jTableArtigosDaRevista.getModel().getRowCount() > 0)
            modelo.removeRow(0);
    }//GEN-LAST:event_jButtonLimparCamposDeCadastroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdicionarArtigo;
    private javax.swing.JButton jButtonCadastrarRevista;
    private javax.swing.JButton jButtonLimparCamposDeCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableArtigosDaRevista;
    private javax.swing.JTextField jTextFieldAnoDaPublicacao;
    private javax.swing.JTextField jTextFieldDiaDaPublicacao;
    private javax.swing.JTextField jTextFieldEditorial;
    private javax.swing.JTextField jTextFieldMancheteDaRevista;
    private javax.swing.JTextField jTextFieldMesDaPublicacao;
    private javax.swing.JTextField jTextFieldNomeDaEditora;
    private javax.swing.JTextField jTextFieldNomeDaRevista;
    private javax.swing.JTextField jTextFieldNumeroDaEdicao;
    // End of variables declaration//GEN-END:variables
}
